[REST] Add https support
jeakfrw/jeak-framework pull request #172
Opened 2020-02-23 18:06 UTC by finnWellers

Fixes #59

2020-03-07 18:02 UTC, MarkTwoFive requested changes

2020-03-07 18:02 UTC, MarkTwoFive commented on src/main/java/de/fearnixx/jeak/service/controller/controller/SparkAdapter.java
> +                    service.halt(403);
I would say that ``400 BAD_REQUEST`` would be a better way of responding to clients not using HTTPS as their request is actually wrong and not just unauthorized. :thinking:  
Also, a possible response body for rejected unencrypted requests could be the following. This would allow developers to recognize what they may have done wrong.
```
{
  "errors": [
    {"message": "Use of HTTPS is mandatory for this endpoint"}
  ]
}
```

2020-03-07 18:02 UTC, MarkL4YG commented
Everything else looks fine to me :slightly_smiling_face: :+1:

2020-03-09 20:00 UTC, finnWellers commented on src/main/java/de/fearnixx/jeak/service/controller/controller/SparkAdapter.java
> +                    service.halt(403);
What would you say to this recommendation? 
https://tools.ietf.org/html/rfc2817#section-4.2

2020-03-22 12:32 UTC, MarkL4YG commented on src/main/java/de/fearnixx/jeak/service/controller/controller/SparkAdapter.java
> +                    service.halt(403);
Looks fine to me. We could use the above-mentioned message body to still respond with valid JSON which would still be human readable.

2020-03-29 12:01 UTC, finnWellers commented on src/main/java/de/fearnixx/jeak/service/controller/controller/SparkAdapter.java
> +                    service.halt(403);
I changed it. When we have other use cases where we want to return other errors, like in #159, we can refactor this part.

2020-03-30 17:56 UTC, MarkTwoFive approved these changes

2020-03-30 17:56 UTC, MarkL4YG commented
Thank you very much 👍 💯

2020-03-30 17:56 UTC, merged